name: SG
version: 1.0
author: devcode
main: me.devcode.SurvivalGames.SG
commands:
  setlobby:
  setspeclobby:
  setspawn1:
  stats:
  start:
  setdmspawn:
  setdmspeclobby:
  setspawn2:
  setspawn3:
  build:
  settop: